version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    container_name: yatube_django
    restart: always
    command: ./web_entrypoint.sh
    volumes:
      - static_volume:/app/web/static
      - /app/web/media:/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
      - static_volume:/app/web/static
      - /app/web/media:/app/web/media 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  static_volume:
  postgresql_volume: