version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/:rw
    env_file:
      - ./.env

  web:
    image: ${DOCKER_USERNAME}/yatube:latest
    restart: always
    volumes:
      - static_volume:/app/static/:rw
      - media_volume:/app/media/:rw
    ports:
     - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw  
      - static_volume:/var/html/static/:rw
      - media_volume:/var/html/media/:rw
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    restart: unless-stopped    
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
  postgresql_volume:
