# Generated by Django 2.2.16 on 2023-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Личные интересы, цели, предпочтения', max_length=500, verbose_name='Немножко о себе'),
        ),
    ]
